formatting:
  image: ghcr.io/prefix-dev/pixi:latest
  stage: test
  script:
    - sudo apt update && sudo apt install git -y
    - pixi run -e test pre-commit run --all-files
  tags:
    - linux

test_linux:
  image: ghcr.io/prefix-dev/pixi:latest
  stage: test
  script:
    - pixi run -e test pytest
  artifacts:
    paths:
      - ./htmlcov
    when: always
    expire_in: "2 days"
  tags:
    - linux
